// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SeattlePetNanny.Data;
using System;

namespace SeattlePetNanny.Migrations
{
    [DbContext(typeof(SeattlePetNannyContext))]
    partial class SeattlePetNannyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeattlePetNanny.Models.Dog", b =>
                {
                    b.Property<int>("DogID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed");

                    b.Property<int>("OwnerId");

                    b.Property<int>("Temperment");

                    b.Property<int>("Weight");

                    b.HasKey("DogID");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("SeattlePetNanny.Models.Owner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DogID");

                    b.Property<int?>("DogID1");

                    b.Property<string>("Email");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("OwnerID");

                    b.HasIndex("DogID1");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("SeattlePetNanny.Models.ReportCard", b =>
                {
                    b.Property<int>("ReportCardID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DogID");

                    b.Property<string>("Report");

                    b.Property<int>("WalkerID");

                    b.HasKey("ReportCardID");

                    b.ToTable("ReportCard");
                });

            modelBuilder.Entity("SeattlePetNanny.Models.Walker", b =>
                {
                    b.Property<int>("WalkerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("WalkerID");

                    b.ToTable("Walker");
                });

            modelBuilder.Entity("SeattlePetNanny.Models.Owner", b =>
                {
                    b.HasOne("SeattlePetNanny.Models.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogID1");
                });
#pragma warning restore 612, 618
        }
    }
}
